#! /usr/bin/env ruby

def showUsage
   puts <<EOF
   "Usage: COMMAND [REPLY_ID|OFFSET|ARTICLE_ID] [SERVER HOST] [SERVER PORT]
       COMMAND: Either POST, LIST, or GET, case insensitive
           POST: post a new article. Content is read from STDIN.
                 REPLY_ID _must_ be present, and equal to 0 if not replying
                 to an existing post.
           LIST: list articles on the server, up to 10 at a time.
                 OFFSET must be present. Use
                 0 to read articles from the beginning.
           GET: get a specific article on the server. ARTICLE_ID must\n
                be present.
EOF
   exit()
end


showUsage unless ARGV.size == 4

cmd = "java -Djava.rmi.server.codebase=http://#{`hostname`.chomp}.mines.edu:#{`pwd`.chomp}/Client/ Client.Client #{ARGV[0]} #{ARGV[1]} #{ARGV[2]} #{ARGV[3]}"
puts cmd
exec(cmd)
